FROM    node

MAINTAINER Isaac Roque Sartori Junio <isaac.sartori@universo.univates.br>

USER    node

ENV     HOME=/home/node/app

RUN     mkdir -p ${HOME} 

WORKDIR ${HOME}

CMD     ["echo", "Você deve criar seu próprio contêiner a partir deste."]

