FROM    node:8.17

MAINTAINER Isaac R. Sartori Junior <isaac.sartori@universo.univates.br>

ENV     NODEJS_VERSION=8.0 \
        HOME=/opt/app-root/src

RUN     mkdir -p ${HOME}

WORKDIR	${HOME}

CMD	["echo", "Você deve criar seu próprio contêiner a partir deste."]
